version: 2

jobs:
  macos:
    macos:
      xcode: "9.2.0"
    steps:
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme VaporExtensions-Package -enableCodeCoverage YES test
      - run: bash <(curl -s https://codecov.io/bash)

  linux:
    docker:
      - image: norionomura/swift:swift-4.1-branch
    steps:
      - checkout
      - run: apt-get update
      - run: apt-get install -yq libssl-dev
      - run: swift build
      - run: swift build -c release
      - run: swift test

workflows:
  version: 2
  tests:
    jobs:
      - linux
      # - macos
